In [5]:
import tensorflow as tf
텐서 = tf.constant([3,4,5])
print(텐서)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


### Tensor

텐서는 기본적인 하나의 자료형.


### Tensor가 왜 필요한가?

input이 x1, x2, x3 이랑 w1, w2, w3 라고 가정했을 때. 각각을 곱해서 더한 것을 하나의 노드로 만들고 싶다.

이걸 파이썬 코드로 만들라면 곱하고 더하고 곱하고 더하고...

행렬을 이용하면 더하고 곱하고 쉽게 할 수 있다! node 값의 계산식이 쉬워진다.


텐서는 아래와 같이 쉬운 연산을 위해서 사용할 수 있다~

#### 사칙연산
* tf.add()
* tf.subtract()
* tf.divide()
* tf.multiply() - 각 요소끼리 곱 연산 (x1*y1, x2*y2 ... )
* tf.matmul() - 행렬의 곱 연산 ((x1,y1)*(x1,y1)

#### 0으로 가득찬 텐서
* tf.zeros()

In [8]:
import tensorflow as tf

텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])
텐서3 = tf.constant([[1,2],
                     [3,4]])
텐서4 = tf.zeros(10)

print(텐서 + 텐서2)
print(tf.add(텐서, 텐서2))
print(텐서4)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
